ServerResourcePacks:
    Gondor:
        16px:
            light:
                url: https://github.com/MCME/RP-Gondor/releases/download/v3.0.4/Gondor.zip
                sha: 7f838c761529237eaf1d9cdc8cd4c439d9cb0770
            footprints:
                url: https://github.com/MCME/RP-Gondor/releases/download/v3.0.4fp/Gondor-footprints.zip
                sha: a8485583bf497c30a4229aeff9dc3a1e9f151feb
rpSettingsDatabase:
    user: xxx
    password: xxx
    dbName: xxx
    ip: localhost
    port: 3306
    dynmap:
        enabled: true
    entityLogger:
        enabled: true
