ServerResourcePacks:
    Human:
        vanilla:
            16px:
                light:
                    url: https://github.com/MCME/RP-Human/releases/download/v3.0.4/Human.zip
                    sha: 7f838c761529237eaf1d9cdc8cd4c439d9cb0770
rpSettingsDatabase:
    user: xxx
    password: xxx
    dbName: xxx
    ip: localhost
    port: 3306
EntityLimit:
    number: 500
    radius: 80
dynmap:
    enabled: true
entityLogger:
    enabled: true
gitHubRpReleases:
    Human:
        owner: EriolEandur
        repo: RP-Gondor
        script: releaseHuman.sh
        path: /opt/mcme-network/bungee-mcme/resourcePacksAutomation/
    Dwarf:
        owner: EriolEandur
        repo: RP-Moria
        script: releaseDwarf.sh
        path: /opt/mcme-network/bungee-mcme/resourcePackAutomation/
inventoryDownload:
    script: updateInventories.sh
    path: /opt/mcme-network/bungee-mcme/resourcePackAutomation/