ServerResourcePacks:
    Human:
        vanilla:
            16px:
                light:
                    url: https://github.com/MCME/RP-Human/releases/download/v3.0.4/Human.zip
                    sha: 7f838c761529237eaf1d9cdc8cd4c439d9cb0770
rpSettingsDatabase:
    user: xxx
    password: xxx
    dbName: xxx
    ip: localhost
    port: 3306
    dynmap:
        enabled: true
    entityLogger:
        enabled: true
