name: ${project.artifactId}
main: com.mcmiddleearth.architect.ArchitectPlugin
version: ${project.version}
author: Eriol_Eandur
load: STARTUP
softdepend: [ProtocolLib,Essentials,dynmap]
depend: [PluginUtils]
api-version: 1.19

commands:
   parrot:
      description: Removes parrots
      usage: /parrot
   get:
      description: Gives user special blocks with changed place behaviour
      usage: /get doors|logs|plants|food|head|slabs|armor|misc
   fbt:
      description: Toggle full brightness on/off.
      usage: /fbt
   vv:
      description: List content in the VoxelSniper plugin directory.
      usage: /vv stenicl|list|delete [subdir] [#pagennumber]
   schlist:
      description: List WorlEdit schematics and subdirectories.
      usage: /schlist <subdir>
   sl:
      description: StencilList generator command.
      usage: /sl create | add | remove |save | show
   random:
      description: Field randomiser command.
      usage: /random [radius #|range # #|probs [#] |material [names]| show | allow | deny | help]
   banner:
      description: Edit banners command
      usage: see /banner help
   armor:
      description: Edit armor stands command
      usage: see /armor help
   rp:
      description: Switch resource packs by command
      usage: /rp Human|Lothlorien|Rohan|Moria|Mordor
   itemblock:
      description: Remove all item block armor stands in a radius
      usage: /itemblock remove <radius>
   inv:
      description: Open special build inventory
      usage: /inv b[lock] | i[tem] 
   nophy:
      description: Manage no phyics list
      usage: /nophy list | add | remove
   architect:
      description: Manage architect plugin
      usage: /architect version | world | weather | reload | dev
   chunkupdate:
      description: Updates chunks around a player
      usage: /chunkupdate <radius>
   chead:
      description: Manage custom heads
      usage: /chead list | reviewlist | submit | accept | reject | rename | delete | reload
   sign:
      description: Edit signs
      usage: /sign <#line> <line text>
   copy:
      description: copy area from cuboid WE selection to your clipboard
      usage: /cp
      aliases: cp
   cut:
      description: cut area from cuboid WE selection to your clipboard
      usage: /ct
      aliases: ct
   paste:
      description: paste your clipboard
      usage: /pst
      aliases: [pst, ps]
   undo:
      description: rolls back your last /paste command(s)
      usage: /un <#steps>
      aliases: [un, ud]
   redo:
      description: restores a previously undone /paste command(s)
      usage: /re <#steps>
      aliases: [re, rd]
   flip:
      description: flips your clipboard
      usage: /flp [x|y|z]
      aliases: [flp, fl]
   rot:
      description: rotate your clipboard along y-axis
      usage: /rt [90|180|270]
      aliases: rt
   viewdistance:
      description: change your client side view distance
      usage: /viewdistance [#viewdistance] | default
      aliases: viewdist
   weselect:
      description: selects we commands to use with block picker
      usage: /weselect <we_command>
      aliases: [wes]
   switchstick:
      description: disables the stick for block interaction
      usage: /switchstick
      aliases: [swst,ss]
permissions:
    architect.*:
        description: Allows to use all features of Architect plugin
        default: op
        children:
            architect.ranks.headDesigner: true
    architect.ranks.headDesigner:
        descriptions: Permission for MCME Head Designer
        default: op
        children:
            architect.ranks.designer: true
            architect.randomiser.allowMaterials: true
            architect.reload: true
            architect.noPhysicsList.edit: true
            architect.voxel.delete: true
            architect.customHeadManager.manager: true
            architect.armorStandEditor.delete: true
            architect.bannerEditor.delete: true
            architect.inventory.reload: true
            architect.inventory.other: true
            architect.get.other: true
            architect.weather: true
            archtiect.resourcePackAdmin: true
            architect.itemBlock: true
            architect.itemBlock.remove: true
            architect.itemBlock.region.limit: true
            architect.itemBlock.region.ignore: true
            architect.itemBlock.region.create: true
    architect.ranks.designer: 
        descriptions: Permission for MCME Designers
        default: op
        children:
            architect.ranks.artist: true
            architect.info: true
            architect.weSchemViewer: true
            architect.voxel.viewer: true
            architect.voxel.stencilListEditor: true
            architect.randomiser.user: true
            architect.get.public: true
            architect.inventory.save: true
            architect.noPhysicsList.exception: true
            architect.copypaste: true
    architect.ranks.artist: 
        descriptions: Permission for MCME Artists
        default: op
        children:
            architect.ranks.adventurer: true
            architect.bannerEditor.save: true
            architect.armorStandEditor.trusted: true
            architect.chunkupdate: true
            architect.get.private: true
            architect.weselect: true
    architect.ranks.adventurer: 
        descriptions: Permission for MCME Adventurers
        default: op
        children:
            architect.hangingEntityEditor: true
            architect.bannerEditor: true
            architect.paintingEditor: true
            architect.cycleBlocks: true
            architect.armorStandEditor: true
            architect.place.halfDoor: true
            architect.place.halfBed: true
            architect.place.torch: true
            architect.place.plant: true
            architect.place.pistonExtension: true
            architect.place.burningFurnace: true
            architect.interactDragonEgg: true
            architect.fullBrightness: true
            architect.resourcePackSwitcher: true
            architect.place.doubleSlab: true
            architect.place.sixSidedLog: true
            architect.get.armor: true
            architect.get.head: true
            architect.get.plants: true
            architect.get.misc: true
            architect.get.doors: true
            architect.get.slabs: true
            architect.get.food: true
            architect.get.logs: true
            architect.getCommand: true
            architect.customHeadManager.user: true  
            architect.inventory: true
            architect.inventory.open: true
            architect.help: true
            architect.noPhysicsList.view: true
            architect.signEditor: true
            architect.viewdistance: true
            architect.switchstick: true
    architect.copypaste:
        description: Allows to use /copy /paste and /rot
        default: op
    architect.copypaste.unlimited: 
        description: Allows to copy / paste unlimited amount of blocks dont crash the server
        default: op
    architect.info: 
        descriptions: Allows to use command /architect version | world | dev
        default: op
    architect.inventory.open:
        description: Allows to open inventories of dispensers, droppers, hoppers, brewing stands, beacons and anvils
        default: op
    architect.inventory:
        description: Allows to open Architect's special build inventories
        default: op
    architect.inventory.save:
        description: Allows to create custom build inventories
        default: op
    architect.inventory.other:
        description: Allows to delete custom build inventories created by other players
        default: op
    architect.inventory.reload:
        description: Allows to reload Architect's special build inventories from config files
        default: op
    architect.chunkupdate:
        description: Allows to use comand /chunkupdate
        default: op
    architect.help:
        description: Allows to use comand /architect help
        default: true
    architect.reload: 
        descriptions: Allows to use command /architect reload
        default: op
    architect.fullBrightness: 
        descriptions: Allows to use command /fbt 
        default: op
    architect.resourcePackSwitcher: 
        descriptions: Allows to use command /rp 
        default: op
    architect.resourcePackAdmin: 
        descriptions: Allows to manage resource packs using command /rp 
        default: op
        children:
            architect.resourcePackSwitcher: true
    architect.place.halfDoor: 
        descriptions: Allows to place half doors
        default: op
    architect.place.halfBed: 
        descriptions: Allows to place half beds
        default: op
    architect.place.torch: 
        descriptions: Allows to place redstone torches
        default: op
    architect.place.doubleSlab: 
        descriptions: Allows to place double slabs
        default: op
    architect.place.plant: 
        descriptions: Allows to place special plants
        default: op
    architect.place.burningFurnace: 
        descriptions: Allows to place and interact with burning furnaces
        default: op
    architect.place.pistonExtension: 
        descriptions: Allows to place piston extensions
        default: op
    architect.place.sixSidedLog: 
        descriptions: Allows to place six sided logs
        default: op
    architect.interactDragonEgg: 
        descriptions: Allows to interact (teleport) dragon egg; doesn't make sense to give to anyone
        default: false
    architect.itemTexture:
        description: Allows to change durability of item in hand to use alternative texture
        default: op
    architect.itemBlock.remove:
        description: Allows to remove item block armor stands in a radius
        default: op
    architect.itemBlock:
        description: Allows to use command /itemblock
        default: op
    architect.itemBlock.region.limit:
        description: Allows to change limit of an item block region
        default: op
    architect.itemBlock.region.create:
        description: Allows to create new item block limit regions
        default: op
    architect.itemBlock.region.ignore:
        description: Allows to ignore itemblock limit of a region
        default: op
    architect.get.armor:
        descriptions: Allows to get coloured leather armor
        default: op
    architect.get.logs: 
        descriptions: Allows to get six sided logs
        default: op
    architect.get.doors: 
        descriptions: Allows to get half doors
        default: op
    architect.get.plants: 
        descriptions: Allows to get plants
        default: op
    architect.get.misc: 
        descriptions: Allows to get miscellanious items
        default: op
    architect.get.food: 
        descriptions: Allows to get food items
        default: op
    architect.get.slabs: 
        descriptions: Allows to get double slabs
        default: op
    architect.get.head: 
        descriptions: Allows to get players head
        default: op
    architect.get.public: 
        descriptions: Allows to create public item sets for /get command
        default: op
    architect.get.private: 
        descriptions: Allows to create private item sets for /get command
        default: op
    architect.get.other: 
        descriptions: Allows to delete/publish/unpublish item sets created by other players
        default: op
    architect.getCommand: 
        descriptions: Allows to use command /get
        default: op
    architect.noPhysicsList.edit: 
        descriptions: Allows to edit the no-physics list
        default: op
        children:
            architect.noPhysicsList.view: true
    architect.noPhysicsList.exception: 
        descriptions: Allows to manage no-physics exception areas
        default: op
    architect.noPhysicsList.view: 
        descriptions: Allows to view the no-physics list
        default: op
    architect.weSchemViewer: 
        descriptions: Allows to use command /schlist
        default: op
    architect.voxel.viewer: 
        descriptions: Allows to use command /vv list | stencil
        default: op
    architect.voxel.delete: 
        descriptions: Allows to use command /vv delete
        default: op
        children:
            architect.voxel.viewer: true
    architect.voxel.stencilListEditor: 
        descriptions: Allows to use command /sl
        default: op
    architect.bannerEditor: 
        descriptions: Allows to use Banner Editor (except save command)
        default: op
    architect.bannerEditor.save: 
        descriptions: Allows to save Banner Editor files and delete own banner files
        default: op
        children:
            architect.bannerEditor: true
    architect.bannerEditor.delete: 
        descriptions: Allows to delete Banner Editor files saved by other players
        default: op
    architect.paintingEditor: 
        descriptions: Allows to use Painting Editor
        default: op
    architect.cycleBlocks: 
        descriptions: Allows to cycle plant growth stages by clicking with stick
        default: op
    architect.hangingEntityEditor: 
        descriptions: Allows to edit hanging Entities
        default: op
    architect.signEditor: 
        descriptions: Allows to use Sign Stand Editor
        default: op
    architect.lecternEditor:
        description: Allows to take books from lecterns
        default: op
    architect.armorStandEditor: 
        descriptions: Allows to use Armor Stand Editor (except storing and deleting files)
        default: op
    architect.armorStandEditor.trusted: 
        descriptions: Allows to store Armor Stand Editor files and delete own files
        default: op
        children:
            architect.armorStandEditor: true
    architect.armorStandEditor.delete: 
        descriptions: Allows to delete Armor Stand Editor files created by other players
        default: op
    architect.randomiser.allowMaterials: 
        descriptions: Allows to change allowed materials for command /random
        default: op
        children:
            architect.randomiser.user: true
    architect.randomiser.user: 
        descriptions: Allows to use command /random (except of /random allow | deny)
        default: op
    architect.customHeadManager.user: 
        descriptions: Allows to use command /chead list | submit
        default: op
    architect.customHeadManager.manager: 
        descriptions: Allows to use all subcommands of command /chead 
        default: op
    architect.weather: 
        descriptions: Allows to change server weather 
        default: op
    architect.checknbt:
        descriptions: Allows to check item NBTs
        default: op
    architect.inventory.ignoreProtection:
        descriptions: Allows to edit inventory content without build permission
        default: op
    architect.viewdistance:
        descriptions: Allows to change client view distance
        default: op